# ----------------------------------------------------------------------------------------------------------------------
# Isy-Fact Configuration
isy:
  logging:
    anwendung:
      name: IsyFact-Standards-Tutorial
      typ: GA
      version: 0.0.0-SNAPSHOT

# ----------------------------------------------------------------------------------------------------------------------
# Spring Configuration
server:
  port: 8081
spring:
  jpa:
    show_sql: true            
    defer-datasource-initialization: true # let jpa create the tables before inserting the data
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  messages:
    basename: resources/nachrichten/fehler
  security:
    user:
      password: password
  sql:
    init:
      mode: always
      data-locations:
        - classpath:data.sql
      continue-on-error: true
